using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CityParser2000
{
    class Building
    {
        public enum BuildingCode
        {
            Empty = 0x00,
            Rubble1 = 0x01,
            Rubble2 = 0x02,
            Rubble3 = 0x03,
            Rubble4 = 0x04,
            RadioactiveWaste = 0x05,
            Trees1 = 0x06,
            Trees2 = 0x07,
            Trees3 = 0x08,
            Trees4 = 0x09,
            Trees5 = 0x0A,
            Trees6 = 0x0B,
            Trees7 = 0x0C,
            SmallPark = 0x0D,
            PowerLine1 = 0x0E,
            PowerLine2 = 0x0F,
            PowerLine3 = 0x10,
            PowerLine4 = 0x11,
            PowerLine5 = 0x12,
            PowerLine6 = 0x13,
            PowerLine7 = 0x14,
            PowerLine8 = 0x15,
            PowerLine9 = 0x16,
            PowerLineA = 0x17,
            PowerLineB = 0x18,
            PowerLineC = 0x19,
            PowerLineD = 0x1A,
            PowerLineE = 0x1B,
            PowerLineF = 0x1C,
            Road1 = 0x1D,
            Road2 = 0x1E,
            Road3 = 0x1F,
            Road4 = 0x20,
            Road5 = 0x21,
            Road6 = 0x22,
            Road7 = 0x23,
            Road8 = 0x24,
            Road9 = 0x25,
            RoadA = 0x26,
            RoadB = 0x27,
            RoadC = 0x28,
            RoadD = 0x29,
            RoadE = 0x2A,
            RoadF = 0x2B,
            Rail1 = 0x2C,
            Rail2 = 0x2D,
            Rail3 = 0x2E,
            Rail4 = 0x2F,
            Rail5 = 0x30,
            Rail6 = 0x31,
            Rail7 = 0x32,
            Rail8 = 0x33,
            Rail9 = 0x34,
            RailA = 0x35,
            RailB = 0x36,
            RailC = 0x37,
            RailD = 0x38,
            RailE = 0x39,
            RailF = 0x3A,
            RailSloped1 = 0x3B,
            RailSloped2 = 0x3C,
            RailSloped3 = 0x3D,
            RailSloped4 = 0x3E,
            TunnelEntrance1 = 0x3F,
            TunnelEntrance2 = 0x40,
            TunnelEntrance3 = 0x41,
            TunnelEntrance4 = 0x42,
            CrossoverRoadPowerLine1 = 0x43,
            CrossoverRoadPowerLine2 = 0x44,
            CrossoverRoadRail1 = 0x45,
            CrossoverRoadRail2 = 0x46,
            CrossoverRailPowerLine1 = 0x47,
            CrossoverRailPowerLine2 = 0x48,
            CrossoverHighway1 = 0x49,
            CrossoverHighway2 = 0x4A,
            CrossoverRoadHighway1 = 0x4B,
            CrossoverRoadHighway2 = 0x4C,
            CrossoverRailHighway1 = 0x4D,
            CrossoverRailHighway2 = 0x4E,
            CrossoverHighwayPowerLine1 = 0x4F,
            CrossoverHighwayPowerLine2 = 0x50,
            BridgeSuspension1 = 0x51,
            BridgeSuspension2 = 0x52,
            BridgeSuspension3 = 0x53,
            BridgeSuspension4 = 0x54,
            BridgeSuspension5 = 0x55,
            BridgeOther1 = 0x56,
            BridgeOther2 = 0x57,
            BridgeOther3 = 0x58,
            BridgeOther4 = 0x59,
            BridgeRail1 = 0x5A,
            BridgeRail2 = 0x5B,
            ElevatedPowerLine = 0x5C,
            OnRamp1 = 0x5D,
            OnRamp2 = 0x5E,
            OnRamp3 = 0x5F,
            OnRamp4 = 0x60,
            Highway1 = 0x61,
            Highway2 = 0x62,
            Highway3 = 0x63,
            Highway4 = 0x64,
            Highway5 = 0x65,
            Highway6 = 0x66,
            Highway7 = 0x67,
            Highway8 = 0x68,
            Highway9 = 0x69,
            BridgeHighway1 = 0x6A,
            BridgeHighway2 = 0x6B,
            SubRail1 = 0x6C,
            SubRail2 = 0x6D,
            SubRail3 = 0x6E,
            SubRail4 = 0x6F,
            ResidentialLower1 = 0x70,
            ResidentialLower2 = 0x71,
            ResidentialLower3 = 0x72,
            ResidentialLower4 = 0x73,
            ResidentialMiddle1 = 0x74,
            ResidentialMiddle2 = 0x75,
            ResidentialMiddle3 = 0x76,
            ResidentialMiddle4 = 0x77,
            ResidentialUpper1 = 0x78,
            ResidentialUpper2 = 0x79,
            ResidentialUpper3 = 0x7A,
            ResidentialUpper4 = 0x7B,
            CommercialGasStation1 = 0x7C,
            CommercialBedAndBreakfast = 0x7D,
            CommercialConvenienceStore = 0x7E,
            CommercialGasStation2 = 0x7F,
            CommercialSmallOffice = 0x80,
            CommercialOffice1 = 0x81,
            CommercialWarehouse = 0x82,
            CommercialToyStore = 0x83,
            IndustrialWarehouse1 = 0x84,
            IndustrialChemicalStorage = 0x85,
            IndustrialWarehouse2 = 0x86,
            IndustrialSubstation = 0x87,
            Construction1 = 0x88,
            Construction2 = 0x89,
            Abandoned1 = 0x8A,
            Abandoned2 = 0x8B,
            ResidentialCheapApartments = 0x8C,
            ResidentialApartments1 = 0x8D,
            ResidentialApartments2 = 0x8E,
            ResidentialNiceApartments1 = 0x8F,
            ResidentialNiceApartments2 = 0x90,
            ResidentialCondominium1 = 0x91,
            ResidentialCondominium2 = 0x92,
            ResidentialCondominium3 = 0x93,
            CommericalShoppingCenter = 0x94,
            CommericalGroceryStore = 0x95,
            CommericalOffice2 = 0x96,
            CommericalResortHotel = 0x97,
            CommericalOffice3 = 0x98,
            CommericalOfficeRetail = 0x99,
            CommericalOffice4 = 0x9A,
            CommericalOffice5 = 0x9B,
            CommericalOffice6 = 0x9C,
            CommericalOffice7 = 0x9D,
            IndustrialWarehouse3 = 0x9E,
            InductrialChemicalProcessing = 0x9F,
            IndustrialFactory1 = 0xA0,
            IndustrialFactory2 = 0xA1,
            IndustrialFactory3 = 0xA2,
            IndustrialFactory4 = 0xA3,
            IndustrialFactory5 = 0xA4,
            IndustrialFactory6 = 0xA5,
            Construction3 = 0xA6,
            Construction4 = 0xA7,
            Construction5 = 0xA8,
            Construction6 = 0xA9,
            Abandoned3 = 0xAA,
            Abandoned4 = 0xAB,
            Abandoned5 = 0xAC,
            Abandoned6 = 0xAD,
            ResidentialLargeApartment1 = 0xAE,
            ResidentialLargeApartment2 = 0xAF,
            ResidentialCondominium4 = 0xB0,
            ResidentialCondominium5 = 0xB1,
            CommercialOfficePark = 0xB2,
            CommercialOfficeTower1 = 0xB3,
            CommercialMiniMall = 0xB4,
            CommercialTheater = 0xB5,
            CommercialDriveIn = 0xB6,
            CommercialOfficeTower2 = 0xB7,
            CommercialOfficeTower3 = 0xB8,
            CommercialParkingLot = 0xB9,
            CommercialHistoricOffice = 0xBA,
            CommercialCorporateHeadquarters = 0xBB,
            IndustrialChemicalProcessing = 0xBC,
            IndustrialLargeFactory = 0xBD,
            IndustrialThingamajig = 0xBE,
            IndustrialFactory7 = 0xBF,
            IndustrialLargeWarehouse = 0xC0,
            IndustrialWarehouse4 = 0xC1,
            Construction7 = 0xC2,
            Construction8 = 0xC3,
            Abandoned7 = 0xC4,
            Abandoned8 = 0xC5,
            PowerplantHydro1 = 0xC6,
            PowerplantHydro2 = 0xC7,
            PowerplantWind = 0xC8,
            PowerplantGas = 0xC9,
            PowerplantOil = 0xCA,
            PowerplantNuclear = 0xCB,
            PowerplantSolar = 0xCC,
            PowerplantMicrowave = 0xCD,
            PowerplantFusion = 0xCE,
            PowerplantCoal = 0xCF,
            CityHall = 0xD0,
            Hospital = 0xD1,
            PoliceStation = 0xD2,
            FireStation = 0xD3,
            Museum = 0xD4,
            BigPark = 0xD5,
            School = 0xD6,
            Stadium = 0xD7,
            Prison = 0xD8,
            College = 0xD9,
            Zoo = 0xDA,
            Statue = 0xDB,
            WaterPump = 0xDC,
            Runway1 = 0xDD,
            Runway2 = 0xDE,
            Pier = 0xDF,
            Crane = 0xE0,
            ControlTower1 = 0xE1,
            ControlTower2 = 0xE2,
            SeaportWarehouse = 0xE3,
            AirportBuilding1 = 0xE4,
            AirportBuilding2 = 0xE5,
            Tarmac = 0xE6,
            F15b = 0xE7,
            Hangar1 = 0xE8,
            SubwayStation = 0xE9,
            Radar = 0xEA,
            WaterTower = 0xEB,
            BusStation = 0xEC,
            RailStation = 0xED,
            ParkingLot1 = 0xEE,
            ParkingLot2 = 0xEF,
            LoadingBay = 0xF0,
            TopSecret = 0xF1,
            CargoYard = 0xF2,
            MayorsHouse = 0xF3,
            WaterTreatmentPlant = 0xF4,
            Library = 0xF5,
            Hangar2 = 0xF6,
            Church = 0xF7,
            Marina = 0xF8,
            MissileSilo = 0xF9,
            DesalinationPlant = 0xFA,
            ArcoPlymouth = 0xFB,
            ArcoForest = 0xFC,
            ArcoDarco = 0xFD,
            ArcoLaunch = 0xFE,
            BraunLlamaDome = 0xFF
        }

        private static readonly Dictionary<BuildingCode, string> buildingNames = new Dictionary<BuildingCode, string>()
        {
            {BuildingCode.Empty, "empty"},
            {BuildingCode.Rubble1, "rubble"},
            {BuildingCode.Rubble2, "rubble"},
            {BuildingCode.Rubble3, "rubble"},
            {BuildingCode.Rubble4, "rubble"},
            {BuildingCode.RadioactiveWaste, "radioactive waste"},
            {BuildingCode.Trees1, "tree"},
            {BuildingCode.Trees2, "trees"},
            {BuildingCode.Trees3, "trees"},
            {BuildingCode.Trees4, "trees"},
            {BuildingCode.Trees5, "trees"},
            {BuildingCode.Trees6, "trees"},
            {BuildingCode.Trees7, "trees"},
            {BuildingCode.SmallPark, "small park"},
            {BuildingCode.PowerLine1, "powerline"},
            {BuildingCode.PowerLine2, "powerline"},
            {BuildingCode.PowerLine3, "powerline"},
            {BuildingCode.PowerLine4, "powerline"},
            {BuildingCode.PowerLine5, "powerline"},
            {BuildingCode.PowerLine6, "powerline"},
            {BuildingCode.PowerLine7, "powerline"},
            {BuildingCode.PowerLine8, "powerline"},
            {BuildingCode.PowerLine9, "powerline"},
            {BuildingCode.PowerLineA, "powerline"},
            {BuildingCode.PowerLineB, "powerline"},
            {BuildingCode.PowerLineC, "powerline"},
            {BuildingCode.PowerLineD, "powerline"},
            {BuildingCode.PowerLineE, "powerline"},
            {BuildingCode.PowerLineF, "powerline"},
            {BuildingCode.Road1, "road"},
            {BuildingCode.Road2, "road"},
            {BuildingCode.Road3, "road"},
            {BuildingCode.Road4, "road"},
            {BuildingCode.Road5, "road"},
            {BuildingCode.Road6, "road"},
            {BuildingCode.Road7, "road"},
            {BuildingCode.Road8, "road"},
            {BuildingCode.Road9, "road"},
            {BuildingCode.RoadA, "road"},
            {BuildingCode.RoadB, "road"},
            {BuildingCode.RoadC, "road"},
            {BuildingCode.RoadD, "road"},
            {BuildingCode.RoadE, "road"},
            {BuildingCode.RoadF, "road"},
            {BuildingCode.Rail1, "rail"},
            {BuildingCode.Rail2, "rail"},
            {BuildingCode.Rail3, "rail"},
            {BuildingCode.Rail4, "rail"},
            {BuildingCode.Rail5, "rail"},
            {BuildingCode.Rail6, "rail"},
            {BuildingCode.Rail7, "rail"},
            {BuildingCode.Rail8, "rail"},
            {BuildingCode.Rail9, "rail"},
            {BuildingCode.RailA, "rail"},
            {BuildingCode.RailB, "rail"},
            {BuildingCode.RailC, "rail"},
            {BuildingCode.RailD, "rail"},
            {BuildingCode.RailE, "rail"},
            {BuildingCode.RailF, "rail"},
            {BuildingCode.RailSloped1, "rail"},
            {BuildingCode.RailSloped2, "rail"},
            {BuildingCode.RailSloped3, "rail"},
            {BuildingCode.RailSloped4, "rail"},
            {BuildingCode.TunnelEntrance1, "tunnel"},
            {BuildingCode.TunnelEntrance2, "tunnel"},
            {BuildingCode.TunnelEntrance3, "tunnel"},
            {BuildingCode.TunnelEntrance4, "tunnel"},
            {BuildingCode.CrossoverRoadPowerLine1, "road/powerline"},
            {BuildingCode.CrossoverRoadPowerLine2, "road/powerline"},
            {BuildingCode.CrossoverRoadRail1, "road/rail"},
            {BuildingCode.CrossoverRoadRail2, "road/rail"},
            {BuildingCode.CrossoverRailPowerLine1, "rail/powerline"},
            {BuildingCode.CrossoverRailPowerLine2, "rail/powerline"},
            {BuildingCode.CrossoverHighway1, "highway/highway"},
            {BuildingCode.CrossoverHighway2, "highway/highway"},
            {BuildingCode.CrossoverRoadHighway1, "road/highway"},
            {BuildingCode.CrossoverRoadHighway2, "road/highway"},
            {BuildingCode.CrossoverRailHighway1, "rail/highway"},
            {BuildingCode.CrossoverRailHighway2, "rail/highway"},
            {BuildingCode.CrossoverHighwayPowerLine1, "highway/powerline"},
            {BuildingCode.CrossoverHighwayPowerLine2, "highway/powerline"},
            {BuildingCode.BridgeSuspension1, "suspension bridge"},
            {BuildingCode.BridgeSuspension2, "suspension bridge"},
            {BuildingCode.BridgeSuspension3, "suspension bridge"},
            {BuildingCode.BridgeSuspension4, "suspension bridge"},
            {BuildingCode.BridgeSuspension5, "suspension bridge"},
            {BuildingCode.BridgeOther1, "bridge"},
            {BuildingCode.BridgeOther2, "bridge"},
            {BuildingCode.BridgeOther3, "bridge"},
            {BuildingCode.BridgeOther4, "bridge"},
            {BuildingCode.BridgeRail1, "rail bridge"},
            {BuildingCode.BridgeRail2, "rail bridge"},
            {BuildingCode.ElevatedPowerLine, "elevated powerline"},
            {BuildingCode.OnRamp1, "on ramp"},
            {BuildingCode.OnRamp2, "on ramp"},
            {BuildingCode.OnRamp3, "on ramp"},
            {BuildingCode.OnRamp4, "on ramp"},
            {BuildingCode.Highway1, "highway"},
            {BuildingCode.Highway2, "highway"},
            {BuildingCode.Highway3, "highway"},
            {BuildingCode.Highway4, "highway"},
            {BuildingCode.Highway5, "highway"},
            {BuildingCode.Highway6, "highway"},
            {BuildingCode.Highway7, "highway"},
            {BuildingCode.Highway8, "highway"},
            {BuildingCode.Highway9, "highway"},
            {BuildingCode.BridgeHighway1, "highway bridge"},
            {BuildingCode.BridgeHighway2, "highway bridge"},
            {BuildingCode.SubRail1, "sub/rail"},
            {BuildingCode.SubRail2, "sub/rail"},
            {BuildingCode.SubRail3, "sub/rail"},
            {BuildingCode.SubRail4, "sub/rail"},
            {BuildingCode.ResidentialLower1, "low-income house"},
            {BuildingCode.ResidentialLower2, "low-income house"},
            {BuildingCode.ResidentialLower3, "low-income house"},
            {BuildingCode.ResidentialLower4, "low-income house"},
            {BuildingCode.ResidentialMiddle1, "middle-income house"},
            {BuildingCode.ResidentialMiddle2, "middle-income house"},
            {BuildingCode.ResidentialMiddle3, "middle-income house"},
            {BuildingCode.ResidentialMiddle4, "middle-income house"},
            {BuildingCode.ResidentialUpper1, "upper-income house"},
            {BuildingCode.ResidentialUpper2, "upper-income house"},
            {BuildingCode.ResidentialUpper3, "upper-income house"},
            {BuildingCode.ResidentialUpper4, "upper-income house"},
            {BuildingCode.CommercialGasStation1, "gas station"},
            {BuildingCode.CommercialBedAndBreakfast, "bed & breakfast"},
            {BuildingCode.CommercialConvenienceStore, "convenience store"},
            {BuildingCode.CommercialGasStation2, "gas station"},
            {BuildingCode.CommercialSmallOffice, "small office"},
            {BuildingCode.CommercialOffice1, "office"},
            {BuildingCode.CommercialWarehouse, "commerical warehouse"},
            {BuildingCode.CommercialToyStore, "toy store"},
            {BuildingCode.IndustrialWarehouse1, "industrial warehouse"},
            {BuildingCode.IndustrialChemicalStorage, "chemical storage"},
            {BuildingCode.IndustrialWarehouse2, "industrial warehouse"},
            {BuildingCode.IndustrialSubstation, "industrial substation"},
            {BuildingCode.Construction1, "construction site"},
            {BuildingCode.Construction2, "construction site"},
            {BuildingCode.Abandoned1, "abandoned building"},
            {BuildingCode.Abandoned2, "abandoned building"},
            {BuildingCode.ResidentialCheapApartments, "cheap apartment"},
            {BuildingCode.ResidentialApartments1, "apartment"},
            {BuildingCode.ResidentialApartments2, "apartment"},
            {BuildingCode.ResidentialNiceApartments1, "nice apartment"},
            {BuildingCode.ResidentialNiceApartments2, "nice apartment"},
            {BuildingCode.ResidentialCondominium1, "condominium"},
            {BuildingCode.ResidentialCondominium2, "condominium"},
            {BuildingCode.ResidentialCondominium3, "condominium"},
            {BuildingCode.CommericalShoppingCenter, "shopping center"},
            {BuildingCode.CommericalGroceryStore, "grocery store"},
            {BuildingCode.CommericalOffice2, "office"},
            {BuildingCode.CommericalResortHotel, "resort hotel"},
            {BuildingCode.CommericalOffice3, "office"},
            {BuildingCode.CommericalOfficeRetail, "office/retail"},
            {BuildingCode.CommericalOffice4, "office"},
            {BuildingCode.CommericalOffice5, "office"},
            {BuildingCode.CommericalOffice6, "office"},
            {BuildingCode.CommericalOffice7, "office"},
            {BuildingCode.IndustrialWarehouse3, "industrial warehouse"},
            {BuildingCode.InductrialChemicalProcessing, "chemical processing"},
            {BuildingCode.IndustrialFactory1, "factory"},
            {BuildingCode.IndustrialFactory2, "factory"},
            {BuildingCode.IndustrialFactory3, "factory"},
            {BuildingCode.IndustrialFactory4, "factory"},
            {BuildingCode.IndustrialFactory5, "factory"},
            {BuildingCode.IndustrialFactory6, "factory"},
            {BuildingCode.Construction3, "construction site"},
            {BuildingCode.Construction4, "construction site"},
            {BuildingCode.Construction5, "construction site"},
            {BuildingCode.Construction6, "construction site"},
            {BuildingCode.Abandoned3, "abandoned building"},
            {BuildingCode.Abandoned4, "abandoned building"},
            {BuildingCode.Abandoned5, "abandoned building"},
            {BuildingCode.Abandoned6, "abandoned building"},
            {BuildingCode.ResidentialLargeApartment1, "large apartment"},
            {BuildingCode.ResidentialLargeApartment2, "large apartment"},
            {BuildingCode.ResidentialCondominium4, "large condominium"},
            {BuildingCode.ResidentialCondominium5, "large condominium"},
            {BuildingCode.CommercialOfficePark, "office park"},
            {BuildingCode.CommercialOfficeTower1, "office tower"},
            {BuildingCode.CommercialMiniMall, "mini-mall"},
            {BuildingCode.CommercialTheater, "theater"},
            {BuildingCode.CommercialDriveIn, "drive-in"},
            {BuildingCode.CommercialOfficeTower2, "office tower"},
            {BuildingCode.CommercialOfficeTower3, "office tower"},
            {BuildingCode.CommercialParkingLot, "parking lot"},
            {BuildingCode.CommercialHistoricOffice, "historic office"},
            {BuildingCode.CommercialCorporateHeadquarters, "corporate headquarters"},
            {BuildingCode.IndustrialChemicalProcessing, "chemical processing"},
            {BuildingCode.IndustrialLargeFactory, "large factory"},
            {BuildingCode.IndustrialThingamajig, "industrial thingamajig"},
            {BuildingCode.IndustrialFactory7, "factory"},
            {BuildingCode.IndustrialLargeWarehouse, "large warehouse"},
            {BuildingCode.IndustrialWarehouse4, "warehouse"},
            {BuildingCode.Construction7, "construction site"},
            {BuildingCode.Construction8, "construction site"},
            {BuildingCode.Abandoned7, "abandoned building"},
            {BuildingCode.Abandoned8, "abandoned building"},
            {BuildingCode.PowerplantHydro1, "hydroelectric powerplant"},
            {BuildingCode.PowerplantHydro2, "hydroelectric powerplant"},
            {BuildingCode.PowerplantWind, "wind powerplant"},
            {BuildingCode.PowerplantGas, "natural gas powerplant"},
            {BuildingCode.PowerplantOil, "oil powerplant"},
            {BuildingCode.PowerplantNuclear, "nuclear powerplant"},
            {BuildingCode.PowerplantSolar, "solar powerplant"},
            {BuildingCode.PowerplantMicrowave, "microwave powerplant"},
            {BuildingCode.PowerplantFusion, "fusion powerplant"},
            {BuildingCode.PowerplantCoal, "coal powerplant"},
            {BuildingCode.CityHall, "city hall"},
            {BuildingCode.Hospital, "hospital"},
            {BuildingCode.PoliceStation, "police station"},
            {BuildingCode.FireStation, "fire station"},
            {BuildingCode.Museum, "museum"},
            {BuildingCode.BigPark, "big park"},
            {BuildingCode.School, "school"},
            {BuildingCode.Stadium, "stadium"},
            {BuildingCode.Prison, "prison"},
            {BuildingCode.College, "college"},
            {BuildingCode.Zoo, "zoo"},
            {BuildingCode.Statue, "statue"},
            {BuildingCode.WaterPump, "water pump"},
            {BuildingCode.Runway1, "runway"},
            {BuildingCode.Runway2, "runway"},
            {BuildingCode.Pier, "pier"},
            {BuildingCode.Crane, "crane"},
            {BuildingCode.ControlTower1, "control tower"},
            {BuildingCode.ControlTower2, "control tower"},
            {BuildingCode.SeaportWarehouse, "seaport warehouse"},
            {BuildingCode.AirportBuilding1, "airport building"},
            {BuildingCode.AirportBuilding2, "airport building"},
            {BuildingCode.Tarmac, "tarmac"},
            {BuildingCode.F15b, "F-15b"},
            {BuildingCode.Hangar1, "hangar"},
            {BuildingCode.SubwayStation, "subway station"},
            {BuildingCode.Radar, "radar"},
            {BuildingCode.WaterTower, "water tower"},
            {BuildingCode.BusStation, "bus station"},
            {BuildingCode.RailStation, "rail station"},
            {BuildingCode.ParkingLot1, "parking lot"},
            {BuildingCode.ParkingLot2, "parking lot"},
            {BuildingCode.LoadingBay, "loading bay"},
            {BuildingCode.TopSecret, "top secret"},
            {BuildingCode.CargoYard, "cargo yard"},
            {BuildingCode.MayorsHouse, "mayor's house"},
            {BuildingCode.WaterTreatmentPlant, "water treatment plant"},
            {BuildingCode.Library, "library"},
            {BuildingCode.Hangar2, "hangar"},
            {BuildingCode.Church, "church"},
            {BuildingCode.Marina, "marina"},
            {BuildingCode.MissileSilo, "missile silo"},
            {BuildingCode.DesalinationPlant, "desalination plant"},
            {BuildingCode.ArcoPlymouth, "plymouth arcology"},
            {BuildingCode.ArcoForest, "forest arcology"},
            {BuildingCode.ArcoDarco, "darco arcology"},
            {BuildingCode.ArcoLaunch, "launch arcology"},
            {BuildingCode.BraunLlamaDome, "braun llama dome"},
        };


        // TODO: Assign building types? This may not be at all needed.
        private enum BuildingType
        {
            Empty,
            Transition,
            Residential,
            Commerical,
            Industrial,
            Municipal,
            Transport,
            PowerSupply,
            WaterSupply,
            Airport,
            Seaport,
            Arcology,
            Military,
        }

        private BuildingCode buildingCode;
        private string buildingName;

        public string BuildingName 
        {
            get { return buildingName; }
            private set {} 
        }

        public Building(BuildingCode code)
        {
            buildingCode = code;
            buildingName = buildingNames[code];
        }

        public static string GetBuildingName(BuildingCode code)
        {
            return buildingNames[code];
        }
    }
}
